/* ==========================================================================
   Sidebar, page, etc. navigation and visualization helper scripts
   ========================================================================== */

$(function () {
  const notFoundPageName = '404.html';
  const contentID = 'article';

  function trimCharFromString(str, char) {
    // Create a regular expression to match the given character at the beginning or end of the string
    const regex = new RegExp(`^${char}|${char}$`, 'g');

    // Use replace() to trim the character from the string
    return str.replace(regex, '');
  }

  function hideTocIfNotNeeded(docObject, forceHide) {
    var shouldHide = forceHide;
    var tocElement = docObject.querySelector('.toc');

    if (tocElement) {
      var tocMenuElement = tocElement.querySelector('.toc__menu');
      if (null == tocMenuElement || false == tocMenuElement.hasChildNodes)
        shouldHide = true;
      if (shouldHide) {
        // TOC is autogenerated via 'include toc.html' so its size is not known prior the call of toc.html
        // Signal emptiness, css will hide if needed based on it and config settings
        // NOTE: Not hiding directly here to behave the same way like the left sidebar does
        tocElement.classList.add('empty');
      }
    }
  }

  function adjustSidebars() {
    // Identify the URL of the loaded page
    var loadedPageUrl = window.location.pathname;

    // Get the "sidebar" element
    var sidebarElement = document.querySelector('.sidebar');
    // If "sidebar" element exists, find the corresponding navigator item within it
    if (sidebarElement) {
      // Get all <a> elements in the navigation list within the "sidebar"
      var navLinks = sidebarElement.querySelectorAll('.nav__list .nav-link');

      // Enumerate through each <a> element and remove the "active" class
      navLinks.forEach(navLink => {
        navLink.classList.remove('active');
      });

      // Find the corresponding navigator item with matching URL within the "sidebar"
      var matchingNavItem = sidebarElement.querySelector('.nav__list .nav-link[href="' + loadedPageUrl + '"]');

      // If a matching item is found, mark it as "active"
      if (matchingNavItem) {
        matchingNavItem.classList.add('active');

        // Sync the browser title too
        title = matchingNavItem.text;
        if (title)
          window.top.document.title = title;

        // Expand all parent ul elements up to the nearest .nav__list
        var parentUl = matchingNavItem.closest('ul');
        while (parentUl) {
          var parentCheckbox = parentUl.previousElementSibling.previousElementSibling;
          if (parentCheckbox && parentCheckbox.tagName === 'INPUT' && parentCheckbox.type === 'checkbox')
            parentCheckbox.checked = true;

          // Check if we reached the top most list container item that is an <ul> with class 'nav__list'
          var immediateParent = parentUl.parentElement;
          if (immediateParent.classList.contains('nav__list'))
            break;

          parentUl = immediateParent.closest('ul');
        }

        // Ensure the active item is visible within the "sidebar"
        // TODO: This one is also not too reliable, browser dependant, get a better solution
        matchingNavItem.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
      }

      hideTocIfNotNeeded(document, false);
    }
  }

  // -------------
  // Function to load content based on relative URL
  // -------------
  function loadContentFromUrl(url, onSuccess, onError) {
    fetch(url)
      .then(response => {
        if (false == response.ok) {
          if (response.status == 404 && url.toLowerCase().indexOf(notFoundPageName) === -1)
            throw new Error(response.status);
          else
            throw new Error('Server returned ' + response.status);
        }
        return response.text();
      })
      .then(html => {
        // Parse the HTML string to create a DOM document
        var parser = new DOMParser();
        var doc = parser.parseFromString(html, 'text/html');
        // Find the "article" element in the parsed document
        var newContent = doc.querySelector(contentID);
        onSuccess(newContent);
      })
      .catch(error => {
        onError(error);
      });
  }

  // Returns the live height of any sticky framing that overlays the top of the
  // content area (currently only the sticky `.masthead`). Measured on demand so
  // we always get the value matching the current viewport / breakpoint / theme,
  // instead of relying on a hardcoded magic number.
  function getStickyTopOffset() {
    var masthead = document.querySelector('.masthead');
    if (!masthead)
      return 0;
    var styles = window.getComputedStyle(masthead);
    if (styles.position !== 'sticky' && styles.position !== 'fixed')
      return 0;
    return Math.ceil(masthead.getBoundingClientRect().height);
  }

  function scrollToAnchor(anchorId, instant) {
    var anchorElement = document.getElementById(anchorId);
    if (!anchorElement)
      return;

    if (instant) {
      var top = anchorElement.getBoundingClientRect().top + window.pageYOffset - getStickyTopOffset();
      window.scrollTo({ top: top, left: 0, behavior: 'auto' });
      return;
    }

    // Smooth-scroll path. Currently unused as call site:
    //   - finalizeContent() always passes instant=true (post-SPA-swap jump).
    //   - In-page anchor clicks (TOC links, header permalink anchors) never reach
    //     this function: the SmoothScroll library binds its own click listener to
    //     'a[href*="#"]' and handles them directly with the same `getStickyTopOffset`.
    // Kept here for future programmatic same-page scrolling needs.
    smoothScroll.animateScroll(anchorElement, null, {
      updateURL: false,
      offset: getStickyTopOffset()
    });
  }

  function scrollContentToTop() {
    // Reset the page scroll on inner-content navigation when no anchor is given.
    // Use instant scroll: the page already has a fade-out / fade-in transition,
    // so animating the scroll on top of it would feel sluggish.
    window.scrollTo({ top: 0, left: 0, behavior: 'auto' });
  }

  function anchorIDFromUrl(url) {
    var anchorId = null;
    var hash = url.hash;
    if (hash && hash.length > 0) {
      var hashIndex = hash.indexOf('#');
      if (hashIndex !== -1)
        anchorId = hash.substring(hashIndex + 1);
    }
    return anchorId;
  }

  // Function to apply all of our custom modifications on the self loaded pages
  function finalizeContent(anchorId) {
    window.logger.log('[Navigation] finalizeContent called for URL:', window.location.pathname);
    // Sync the sidebar with the current page url, migth be out of sync when the page is loaded initially from an inner url
    adjustSidebars();
    // There might be nav-links in the loaded new content as well (e.g.Next / Prev buttons
    // so, handle the links here as the last action
    updateNavLinks();
    // Add page heading anchors
    addPageAnchors();
    // Add toc to anchor scrolling
    addTOCScrolling();
    // Add code block enhancements
    if (ClipboardJS.isSupported())
      addCodeBlocksTitle();
    // Add content tooltips
    addContentTooltips();
    // Update contribution buttons to point to the correct source files
    if (typeof updateContributionButtons === 'function')
      updateContributionButtons();
    // Try to scroll to a given anchor, if any
    // `finalizeContent` runs after a SPA content swap, so anchor jumps are
    // always cross-page here -- request an instant jump (no smooth scroll).
    if (anchorId) {
      // For a cross-page navigation the new content has already faded in, an extra
      // smooth scroll on top of that just makes the (unavoidable) max-scroll
      // clamping at the end of the document visible (so, scroll to anchors will not always be accurate).
      // Jump instantly instead.
      scrollToAnchor(anchorId, true);
    }
    else
      scrollContentToTop();
    // Clear any focus (e.g back navigation keeps the previously clicked link focused)
    clearFocus();
    // Forcibly hide the search content that can remain open in certain back and force navigation cases
    hideSearch();
  }

  function updateContentFromUrl(url) {
    var currContent = document.querySelector(contentID);

    loadContentFromUrl(
      url,
      newContent => {
        // FIXME: This does not work, double check
        currContent.scrollTop;
        // As a workaround of the above, empty the old content, and with a short delay only, load the new one
        currContent.innerHTML = '';

        // Replace the old content, but only with a small delay, to make sure the content reset takes effect
        setTimeout(function () {
          // Replace the old content with the loaded content
          currContent.parentNode.replaceChild(newContent, currContent);

          // Add all our custom modifications to all the self loaded pages
          finalizeContent(anchorIDFromUrl(url));
        }, 100);
      },
      error => {
        if (error == "Error: 404") {
          var baseURL = window.location.origin;
          var notFoundURL = baseURL + '/' + docPrefix() + notFoundPageName;

          updateContentFromUrl(notFoundURL);
        }
        else {
          currContent.innerHTML = '<h3>Sorry, there was a problem loading the content!</h3>(' + error + ')';
          window.logger.error("[Navigation] Error loading content, " + error)
        }
      }
    );
  }

  // -------------
  // Functions to handle link clicks
  // -------------
  function getCollectionFromDocPath(url) {
    var collection = '';
    var parts = trimCharFromString(url.pathname, '/').split('/');

    if (docRoot == '') {
      collection = parts[0];
    }
    else {
      var docIndex = parts.indexOf(docRoot);

      // If 'docRoot' is found or it is not the last segment, return the next part after it as the collection name
      if (docIndex !== -1 && docIndex !== parts.length - 1)
        collection = parts[docIndex + 1];
    }
    return collection;
  }

  function sameCollection(url1, url2) {
    var collection1 = getCollectionFromDocPath(url1);
    var collection2 = getCollectionFromDocPath(url2);

    return collection1 === collection2;
  }

  function handleNavLinkClick(event) {
    if (!event.shiftKey && !event.ctrlKey && !event.altKey && !event.metaKey) {
      if (tooltipTarget)
        hideTooltip(true);

      var updated = false;
      // Get the relative URL value and update the browser URL
      // Use originalTarget (Firefox) or target (all other browsers) to get the clicked element
      var anchorElement = (event.originalTarget || event.target).closest('a');

      if (anchorElement) {
        var url = new URL(anchorElement.href);

        // The search-help (i) link points to a root-level page (e.g.
        // `/lunr_search_help.html`) which is not part of any documentation
        // collection, so `sameCollection()` returns false and we would fall
        // through to a full page reload. Force the SPA path for it (and any
        // future link that opts in via the `.spa-load` marker class).
        var forceSpa = anchorElement.classList.contains('search-help') ||
                       anchorElement.classList.contains('spa-load');

        // Try to load into the inner content frame only if the collection has not changed
        // Otherwise let the original click flow take effect, as the nav bar must be reloaded too
        // for a different collection
        if (url.origin === window.location.origin && anchorElement.target !== '_blank' &&
            (forceSpa || sameCollection(url, window.location))) {
          // Prevent default navigation behavior, we will use our content load method
          event.preventDefault();

          var urlStr = url.pathname + url.hash;
          updated = (urlStr != window.location.pathname + window.location.hash);

          // Update the browser URL
          history.pushState(null, null, url);

          // Load content based on the updated relative URL
          // but only if the url has changed
          if (updated)
            updateContentFromUrl(url);
          else
            // Same-page SPA click (e.g. the search-help (i) icon clicked
            // while already on /lunr_search_help.html). No content swap, so
            // `finalizeContent` -- which would normally close the search
            // overlay -- does not run. Close it here instead.
            hideSearch();
        }
        // Clear focus from the clicked element, as we have other visualization for the selected items
        event.target.blur();
      }
      if (false == updated) {
        window.logger.debug("[Navigation] Different collection item or new tab/page requested, loading full page...")
      }
    }
  }

  function updateNavLinks(event) {
    // Attach click event listeners to all links with class 'nav-link'
    var navLinks = document.querySelectorAll('.nav-link');
    navLinks.forEach(function (link) {
      link.addEventListener('click', handleNavLinkClick);
    });
  }

  // -------------
  // TOC smooth scrolling
  // -------------
  // Both SmoothScroll and Gumshoe accept a function for `offset`, evaluated on
  // every scroll/spy tick, so the offset always reflects the current sticky
  // masthead height (which varies with viewport / breakpoint / theme).
  var smoothScroll = new SmoothScroll('a[href*="#"]', {
    offset: getStickyTopOffset,
    speed: 400,
    speedAsDuration: true,
    durationMax: 500
  });

  function addTOCScrolling() {
    // Gumshoe scroll spy init
    if ($("nav.toc a").length > 0) {
      var spy = new Gumshoe("nav.toc a", {
        // Active classes
        navClass: "active", // applied to the nav list item
        contentClass: "active", // applied to the content

        // Nested navigation
        nested: false, // if true, add classes to parents of active link
        nestedClass: "active", // applied to the parent items

        // Offset & reflow
        offset: getStickyTopOffset, // how far from the top of the page to activate a content area
        reflow: true, // if true, listen for reflows

        // Event support
        events: true // if true, emit custom events
      });
    }
  }

  // -------------
  // Add anchors for headings
  // -------------
  function addPageAnchors() {
    // FIXME: This magic 6 must be maintained together now with generate_links.rb (and other places ?!), eliminate it!
    $('.page__content').find('h1, h2, h3, h4, h5, h6').each(function () {
      var id = $(this).attr('id');
      if (id) {
        var anchor = document.createElement("a");
        anchor.className = 'header-link';
        anchor.href = '#' + id;
        anchor.innerHTML = '<span class=\"sr-only\">Permalink</span><i class=\"fab fa-slack-hash\"></i>';
        anchor.title = "Permalink";
        $(this).append(anchor);
      }
    });
  }

  // To support page links even better if possible in case the page has no description / subtitle, but has some text 
  // right after the title and before the first heading is presented, it will be treated as the description and will be handled here.
  // This part should also handle the case when only the title presented. (a.k.a. not showing the tooltip in that case),
  // also responsible to create a uniform look and fell both for page title tooltips and other link tooltips. 
  //
  function alterContentForTooltip(content, url, isFullPageContent, isTextTooltip) {
    var newContent = null;

    if (isTextTooltip) {
      // This would give the saem result as for the other tooltip contents
      // but this kind of tooltip close to a real, one liner tooltip
      // <p> would add huge paddings around it
      // TODO: Add a better, musch more tiny tooltip look
      // newContent = "<p>" + content + "</p>";
      newContent = content;
    }
    else {
      let tempContainer = document.createElement('div');
      tempContainer.innerHTML = content;

      hideTocIfNotNeeded(tempContainer, true);

      // Strip the contribution sidebar (View / Edit / Report buttons from
      // `_includes/page__contribution.html`) -- it makes no sense inside a
      // tooltip preview and just clutters the surface.
      var contribAside = tempContainer.querySelector('.contrib');
      if (contribAside)
        contribAside.remove();

      // Remove/Override some default title style formatting to look better in the tooltip
      var pageTitle = tempContainer.querySelector('#page-title');
      if (pageTitle == null) {
        // If there is no page title, replace the first heading with an item looks and behaves like the page title
        // to have similar result both for page title tooltips and other link item tooltips
        // FIXME: This magic 6 must be maintained together now with generate_links.rb (and other places ?!), eliminate it!
        var firstHeading = tempContainer.querySelector("h2, h3, h4, h5, h6");
        if (firstHeading) {
          // Everything bellow must exist, so intentionally there's no error handling, let it rise
          pageTitle = document.querySelector('#page-title').cloneNode(true);
          pageTitle.id = firstHeading.id;

          const anchorElement = pageTitle.querySelector("a");
          anchorElement.textContent = firstHeading.textContent;
          anchorElement.href = url;

          tempContainer.replaceChild(pageTitle, firstHeading);
        }
      }
      pageTitle.style.marginTop = '1em';

      newContent = tempContainer.innerHTML
      // remove unnecessary, reqursive inner content tooltips
      newContent = newContent.replace(/\bcontent-tooltip\b/g, '');
    }

    return newContent;
  }

  function loadContentPartFrom(url, onSuccess, onError) {
    // If no anchor with heading id, use the page title with id=""
    var startHeadingId = 'page-title'
    // Extract the anchor part of the URL
    var hashIndex = url.indexOf('#');
    var hasAnchor = (hashIndex !== -1);

    if (hasAnchor)
      startHeadingId = url.substring(hashIndex + 1);

    loadContentFromUrl(
      url,
      newContent => {
        var content = '';
        var startHeading = newContent.querySelector('#' + startHeadingId);

        if (startHeading) {
          var heading = startHeading.outerHTML; // Include the starting <h> element itself
          var description = newContent.querySelector('#page-description');

          if (false == hasAnchor &&  description && description.outerHTML.length > 0) {
            content = description.outerHTML;
          }
          else {
            var nextSibling = startHeading.nextElementSibling;

            // If handling a page title it will not have next sibling normally at all (we are removed and handling differently the description from the generated page)
            // In that case the description is all the normal texts parts in the content, from the top (right bellow the title) to the first heading <h1-6>, try to get, it if there's any.
            // If not presented, drop the whole content, return an empty one (a.k.a. do not show title only tooltips)
            if (nextSibling == null && false == hasAnchor) {
              startHeading = newContent.querySelector('.page__content');
              nextSibling = startHeading.firstElementChild;
              // First element is the TOC, skip it to be able to produce an empty content
              if (nextSibling && nextSibling.classList.contains('sidebar__right'))
                nextSibling = nextSibling.nextElementSibling;
            }
            // Collect all siblings until the next heading or the end of the initial content
            // FIXME: This magic 6 must be maintained together now with generate_links.rb (and other places ?!), eliminate it!
            while (nextSibling && nextSibling.tagName !== 'H1' && nextSibling.tagName !== 'H2' && nextSibling.tagName !== 'H3' && nextSibling.tagName !== 'H4' && nextSibling.tagName !== 'H5' && nextSibling.tagName !== 'H6') {
              content += nextSibling.outerHTML;
              nextSibling = nextSibling.nextElementSibling;
            }
          }
          
          if (content.length != 0 || hasAnchor)
            content = heading + content;

          onSuccess(content);
        }
        else
          onError('Start heading not found by ID: ' + startHeadingId);
      },
      error => {
        onError(error);
      }
    );
  }

  // -------------
  // Tooltip generation and handling
  // -------------
  const toolTipArrowHalfSize = 10; /* $tooltip-arrow-half-size  -> _variables.scss & _navigation.scss - .tooltip:before */
  var contentTooltip = null;
  var tooltipRenderer = null;
  var tooltipTarget = null;
  var tooltipToTargetRelativePosition = null;
  var elementUnderCursor = null;
  var shouldShowTooltip = false;
  var showTimeoutFuncID;
  var hideTimeoutFuncID;

  function setTooltipArrowPosition(posName, position) {
    var newPosition = position + 'px';
    contentTooltip.style.setProperty(posName, newPosition);
  }

  function setTooltipPos(event, tooltipTarget, alignment, isTextTooltip) {
    const targetRect = tooltipTarget.getBoundingClientRect();
    var computedTargetStyle = window.getComputedStyle(tooltipTarget);
    var lineHeight = parseFloat(computedTargetStyle.getPropertyValue('line-height'));
    // NOTE: The content of the targeted tooltip is still not yet calculated correctly here, as it is invisible, and getting visible is animated multiple ways
    //       use, the always visible, not animated at all, but offscreen pair of it (tooltipRenderer) for rendered size calculations.
    //       To get this work all the animation styles must be removed in the css (_navigations.scss) for #tooltipRenderer
    // TODO: Now we have the correct tooltip content via teh tooltipRenderer trick.
    //       Prevent tooltip overflow on window edges in all directions.

    // Reset any width overrides from a previous, taller tooltip so the
    // CSS defaults (responsive max-width per .tooltip / .text-content / .full-content variants) apply first.
    contentTooltip.style.width = '';
    contentTooltip.style.maxWidth = '';
    tooltipRenderer.style.width = '';
    tooltipRenderer.style.maxWidth = '';

    var viewportHeight = window.innerHeight;
    var viewportWidth = window.innerWidth;
    var bottomMargin = 24;

    // Compute the eventual top position (independent of tooltip width)
    // so we can decide whether the tooltip would run off the bottom
    // and -- if so -- whether widening it would shorten it enough.
    const mouseX = event.clientX;
    var multilineUpperPart = false == isTextTooltip
      && tooltipTarget.getClientRects().length > 1
      && mouseX > targetRect.x + targetRect.width / 2;
    var posY = (hasMastHead ? 0 : document.documentElement.scrollTop)
             + targetRect.top
             + targetRect.height / (multilineUpperPart ? 2 : 1);
    var contentTooltipTop = posY + toolTipArrowHalfSize;
    var visibleTop = hasMastHead ? contentTooltipTop : (contentTooltipTop - document.documentElement.scrollTop);
    var availableBelow = viewportHeight - visibleTop - bottomMargin;

    // Adaptive width: if the rendered tooltip is taller than it is wide
    // (a narrow column is hard to read), grow it wider until it becomes
    // roughly square or hits a sensible cap. Re-measure on the offscreen
    // tooltipRenderer at each step.
    // Caps applied (whichever is smaller):
    //   - 2/3 of the viewport width (full-width tooltips look ugly)
    //   - viewportWidth - 2*sideGap (keep a margin on both sides)
    //   - the width at which the box would become wider than tall
    //     (height should stay >= width)
    // Note: This runs regardless of whether the tooltip would overflow
    // vertically -- on tall screens a long tooltip can fit but still look
    // like an ugly narrow strip; widen it anyway for readability.
    var sideGap = 24;
    var measure = function () { return tooltipRenderer.getBoundingClientRect(); };
    var tooltipRect = measure();
    var widthCap = Math.max(200, Math.min(Math.floor(viewportWidth * 2 / 3), viewportWidth - 2 * sideGap));
    var stepFactor = 1.5;
    var maxSteps = 6;
    while (tooltipRect.width < widthCap
           && tooltipRect.width < tooltipRect.height
           && maxSteps-- > 0) {
      var nextWidth = Math.min(widthCap, Math.ceil(tooltipRect.width * stepFactor));
      // Do not let the tooltip become wider than tall.
      if (nextWidth > tooltipRect.height) nextWidth = Math.floor(tooltipRect.height);
      if (nextWidth <= tooltipRect.width) break;
      tooltipRenderer.style.maxWidth = nextWidth + 'px';
      tooltipRenderer.style.width = nextWidth + 'px';
      var newRect = measure();
      if (newRect.height >= tooltipRect.height) {
        // Extra width did not help (content already on a single line / hard line breaks); revert and stop.
        tooltipRect = newRect;
        break;
      }
      tooltipRect = newRect;
    }
    if (tooltipRenderer.style.width) {
      contentTooltip.style.maxWidth = tooltipRenderer.style.maxWidth;
      contentTooltip.style.width = tooltipRenderer.style.width;
    }

    var tooltipWidth = tooltipRect.width;
    var pos = new DOMPoint();

    var xShift = (alignment == 'tooltip-align-left' ? tooltipWidth : (alignment == 'tooltip-align-center' ? tooltipWidth / 2 : 0));
    pos.x = mouseX; // Use now mouse X instead - Math.max(0, pos.x + document.documentElement.scrollLeft + targetRect.left);
    pos.x -= xShift;

    pos.y = posY;

    var tooltipArrowHorizontalPadding = (4 * toolTipArrowHalfSize) * (alignment == 'tooltip-align-left' ? 1 : (alignment == 'tooltip-align-right' ? -1 : 0));

    var contentTooltipLeft = pos.x + tooltipArrowHorizontalPadding;
    // contentTooltipTop was already computed above (it only depends on
    // the target geometry, not on the tooltip width).

    // Arrow horizontal anchor: center of the target element. For
    // multi-line (wrapped) targets only the line fragment under the
    // cursor matters. getClientRects() returns one DOMRect per line
    // fragment.
    var arrowAnchorX = targetRect.left + targetRect.width / 2;
    var lineRects = tooltipTarget.getClientRects();
    if (lineRects && lineRects.length > 1) {
      var mouseY = event.clientY;
      for (var i = 0; i < lineRects.length; i++) {
        var lr = lineRects[i];
        if (mouseY >= lr.top && mouseY <= lr.bottom) {
          arrowAnchorX = lr.left + lr.width / 2;
          break;
        }
      }
    }

    // Make sure the tooltip box actually overlaps the anchor X. If the
    // alignment-derived placement would put the anchor outside the
    // tooltip's horizontal range (so the arrow could not point at it),
    // slide the whole tooltip left or right just enough to bring the
    // anchor inside, leaving room for the arrow on either side.
    var sideMargin = 3 * toolTipArrowHalfSize;
    if (arrowAnchorX < contentTooltipLeft + sideMargin) {
      contentTooltipLeft = arrowAnchorX - sideMargin;
    }
    else if (arrowAnchorX > contentTooltipLeft + tooltipWidth - sideMargin) {
      contentTooltipLeft = arrowAnchorX - tooltipWidth + sideMargin;
    }

    // Keep the tooltip on-screen horizontally with a visible side gap
    // (sideGap is the same value used by the width cap above).
    if (contentTooltipLeft < sideGap) contentTooltipLeft = sideGap;
    if (contentTooltipLeft + tooltipWidth > viewportWidth - sideGap)
      contentTooltipLeft = viewportWidth - sideGap - tooltipWidth;

    contentTooltip.style.left = contentTooltipLeft + 'px';

    // Flip decision: when there's not enough room below the anchor to
    // show a meaningful slice of the tooltip, but more room is available
    // above, place the tooltip above the anchor and let CSS rotate the
    // arrow (.tooltip-flipped:before) so it points down at the anchor.
    var renderedHeight = tooltipRect.height;
    var anchorTopVisible = targetRect.top;
    var anchorTopAbsolute = (hasMastHead ? 0 : document.documentElement.scrollTop)
                          + targetRect.top;
    var availableAbove = anchorTopVisible - bottomMargin - toolTipArrowHalfSize;
    // "Below is too tight" if we'd show less than half the tooltip and
    // less than ~180 px in absolute terms; never flip just because
    // there's a slight overflow when most of the content already fits.
    var minVisibleBelow = Math.min(180, Math.max(80, renderedHeight * 0.5));
    var wouldScrollBelow = renderedHeight > availableBelow;
    var wouldScrollAbove = renderedHeight > availableAbove;
    // Flip when:
    //   1. below is squeezed and above offers more room, OR
    //   2. the tooltip would have to scroll below but fits fully above
    //      (no scrollbar is nicer than scrollbar when both sides are
    //      otherwise viable).
    var flip = (availableBelow < minVisibleBelow && availableAbove > availableBelow)
            || (wouldScrollBelow && !wouldScrollAbove);

    if (flip) {
      contentTooltip.classList.add('tooltip-flipped');
      var heightForAbove = Math.min(renderedHeight, availableAbove);
      if (heightForAbove < 80) heightForAbove = 80;
      var topPos = anchorTopAbsolute - toolTipArrowHalfSize - heightForAbove;
      contentTooltip.style.top = topPos + 'px';
    }
    else {
      contentTooltip.classList.remove('tooltip-flipped');
      contentTooltip.style.top = contentTooltipTop + 'px';
    }

    // Place the arrow at the anchor X, relative to the (possibly shifted)
    // tooltip left edge. The vertical anchor (top vs. bottom of the
    // tooltip) is driven by the .tooltip / .tooltip-flipped CSS rules.
    var arrowLeftInTooltip = arrowAnchorX - contentTooltipLeft - toolTipArrowHalfSize;
    setTooltipArrowPosition('--tooltip-arrow-left', arrowLeftInTooltip);
    if (!flip) {
      setTooltipArrowPosition('--tooltip-arrow-top', -1 * toolTipArrowHalfSize);
    }

    // Vertical fit-to-viewport: cap the inner scroll container to the
    // currently-used side (above when flipped, below otherwise).
    var scrollEl = contentTooltip.querySelector('.tooltip-scroll');
    if (scrollEl) {
      var availableSpace = flip ? availableAbove : availableBelow;
      if (availableSpace > 0 && renderedHeight > availableSpace) {
        scrollEl.style.maxHeight = Math.max(80, availableSpace) + 'px';
        scrollEl.style.overflowY = 'auto';
      }
      else {
        // Reset so the next, smaller, tooltip is not stuck at a previous max-height.
        scrollEl.style.maxHeight = '';
        scrollEl.style.overflowY = '';
      }
    }
  }

  function getRealZIndex(element) {
    if (element == null)
      return null;

    var zIndex = getComputedStyle(element).zIndex;
    // If the element's z-index is not auto, return it
    if (zIndex !== "auto")
      return parseInt(zIndex);
    else {
      // If the element's z-index is auto, traverse the parent hierarchy
      var parent = element.parentElement;
      var highestZIndex = null;
      while (parent) {
        var parentZIndex = getComputedStyle(parent).zIndex;
        if (parentZIndex !== "auto") {
          var zIndexValue = parseInt(parentZIndex);
          if (highestZIndex === null || zIndexValue > highestZIndex) {
            highestZIndex = zIndexValue;
          }
        }
        parent = parent.parentElement;
      }
      return highestZIndex;
    }
  }

  function setTooltipStyle(alignment, isFullPageContent, isTextTooltip) {
    if (isTextTooltip) {
      contentTooltip.classList.add("text-content-tooltip");
      tooltipRenderer.classList.add("text-content-tooltip");
    }
    else {
      contentTooltip.classList.remove("text-content-tooltip");
      tooltipRenderer.classList.remove("text-content-tooltip");
    }
    if (isFullPageContent) {
      contentTooltip.classList.add("full-content-tooltip");
      tooltipRenderer.classList.add("full-content-tooltip");
    }
    else {
      contentTooltip.classList.remove("full-content-tooltip");
      tooltipRenderer.classList.remove("full-content-tooltip");
    }
    contentTooltip.classList.remove('tooltip-align-left', 'tooltip-align-center', 'tooltip-align-right');
    tooltipRenderer.classList.remove('tooltip-align-left', 'tooltip-align-center', 'tooltip-align-right');
    contentTooltip.classList.add(alignment);
    tooltipRenderer.classList.add(alignment);
  }

  function setTooltipZIndex() {
    var zIndex = getRealZIndex(tooltipTarget);

    if (zIndex)
      contentTooltip.style.zIndex = zIndex;
    else {
      /* If the parent hierarchy has no explicit z-index setting, use a higher than the default
         FIXME: messy, as a deafult is not defined anywhere, only in the (s)css files, 
                add a know global in the _variables.scss and use it here, and everywhere in the scss files where the z-index is set
                (like _magnific-popup,scss does)
         Now, it seems, the 0 is the default and only the following values are used
            - 100000 - screen reader
            - 9999, 999 - modals
            - 1040+ - magnific-popup
            - 20 - skip-link
            - 20, 1 - sidebar author__urls-wrapper
            - 20, 10 - .nav__list .nav__items label
            - 20 - masthead
            - 10 - masthead nav
            - 10 - sidebar__right
            - 10 - archive__item a
            - 5 - archive__item-caption
            - 5 - page__hero-caption
       */
      zIndex = 5;
    }
    /*
     NOTE: Currently we only have to care about tooltips for
           - page content items
                max z-index - 0
           - masthead items (e,g, buttons)
                max z-index - 20
    so, simply currently just setting one higher value for the tooltip than the target. 
    */
    contentTooltip.style.zIndex = zIndex + 1;
  }

  function showTooltip(event, tooltipText, alignment, isFullPageContent, isTextTooltip) {

    // Globally disabled via the settings panel? Bail out early so no
    // hover preview ever appears.
    if (typeof getCookie === 'function'
        && getCookie('settings-tooltips-enabled', 'true', true) === 'false')
      return;

    // Wrap the content in an inner scroll container so vertical capping
    // (when the tooltip would overflow the viewport) does not clip the
    // .tooltip:before arrow, which lives at a negative top offset.
    var wrapped = '<div class="tooltip-scroll">' + tooltipText.innerHTML + '</div>';
    contentTooltip.innerHTML = wrapped;
    tooltipRenderer.innerHTML = wrapped;

    setTooltipStyle(alignment, isFullPageContent, isTextTooltip);
    setTooltipZIndex();
    setTooltipPos(event, tooltipTarget, alignment, isTextTooltip);
    
    shouldShowTooltip = true;
    
    clearTimeout(hideTimeoutFuncID);
    clearTimeout(showTimeoutFuncID);
    // Read the user-configurable tooltip show delay (settings panel).
    var tooltipDelay = 100;
    if (typeof getCookie === 'function') {
      var d = parseInt(getCookie('settings-tooltip-delay', '100', true), 10);
      if (!isNaN(d) && d >= 0) tooltipDelay = d;
    }
    showTimeoutFuncID = setTimeout(function () {
      if (shouldShowTooltip) {
        contentTooltip.classList.add('visible');
      }
    }, tooltipDelay);
  }

  function shouldHideTooltip(activeTarget) {
    // The cursor is still "inside" the hover hint tooltip only when it is
    // over the hint container itself (#tooltip == contentTooltip) or one
    // of its descendants. Other .tooltip elements (e.g. the settings
    // panel popover) are unrelated popovers and must NOT keep the hover
    // hint visible.
    return ((tooltipTarget == null || activeTarget != tooltipTarget) && (contentTooltip == null || (activeTarget != contentTooltip && activeTarget != null && false == contentTooltip.contains(activeTarget))));
  }

  function hideTooltip(withDelay) {
    function doHideTooltip() {
      if (false == shouldShowTooltip && tooltip)
        contentTooltip.classList.remove('visible');
      tooltipTarget = null;
      tooltipToTargetRelativePosition = null;
      // TODO: Here is the gotcha
      //       - this cannot be done directly as it will kill the transition animation effects
      //       - not doing it could lead to occupied, overflowing area that will break the auto srinking back the container 
      //         to its content minimum size once the overflowing tooltip got 'invisible'
      //         actually this issue will go away once we limit the tooltip oveflowing in any direction from the window
      setTimeout(function () {
        if (tooltipTarget == null && false == shouldShowTooltip) {
          contentTooltip.innerHTML = '';
          tooltipRenderer.innerHTML = '';
        }
      }, 100);
    }

    shouldShowTooltip = false;

    if (withDelay) {
      clearTimeout(hideTimeoutFuncID);
      // User-configurable hide delay (settings panel). Lets the cursor
      // travel into the tooltip to click links inside it.
      var hideDelay = 50;
      if (typeof getCookie === 'function') {
        var hd = parseInt(getCookie('settings-tooltip-hide-delay', '50', true), 10);
        if (!isNaN(hd) && hd >= 0) hideDelay = hd;
      }
      hideTimeoutFuncID = setTimeout(function () {
        doHideTooltip();
      }, hideDelay);
    }
    else
      doHideTooltip();
  }

  function addContentTooltips() {
    var tooltipElements = document.querySelectorAll('.content-tooltip');
    contentTooltip = document.getElementById('tooltip');
    tooltipRenderer = document.getElementById('tooltipRenderer');
    hideTooltip();

    tooltipElements.forEach(function (element) {
      var tooltipText = document.createElement('span');
      tooltipText.className = 'tooltip-text';
      tooltipText.textContent = "";
      element.appendChild(tooltipText);

      element.addEventListener('mouseover', function (event) {
        var isFullPageContent = element.classList.contains('full-content-tooltip');
        var isTextTooltip = element.classList.contains('text-content-tooltip');
        var alignment = (element.classList.contains('tooltip-align-left') ? 'tooltip-align-left' : (element.classList.contains('tooltip-align-center') ? 'tooltip-align-center' : 'tooltip-align-right'));

        tooltipTarget = element;
        tooltipToTargetRelativePosition = null;

        // Load only once per page load
        if (tooltipText.innerHTML === '') {
          var url = element.href;

          function onSuccess(newContent) {
            if (typeof (newContent) === 'object' && 'innerHTML' in newContent)
              newContent = newContent.innerHTML;
            newContent = alterContentForTooltip(newContent, url, isFullPageContent, isTextTooltip);

            if (newContent.length > 0) {              
              tooltipText.innerHTML = newContent; // cache for reuse
              showTooltip(event, tooltipText, alignment, isFullPageContent, isTextTooltip);
            }
            else {
              // Quick navigation from another link with tooltip to this link would keep alive the previous tooltip
              // force close it, as we don't have tooltip for the current and this is the live hovered one.
              hideTooltip(false);
            }
          }

          function onError(error) {
            // Quick navigation from another link with tooltip to this failing link would keep alive the previous tooltip
            // force close it, as we don't have tooltip for the current and this is the live hovered one.
            hideTooltip(false);
            window.logger.error('[Navigation] Error loading the tooltip content!' + error);
          }
          
          if (isTextTooltip) {
            newContent = alterContentForTooltip(element.getAttribute("data-tooltip-text"), null, isFullPageContent, isTextTooltip);
            if (newContent.length > 0) {
              tooltipText.innerHTML = newContent;
              showTooltip(event, tooltipText, alignment, isFullPageContent, isTextTooltip);
            }
          }
          else if (isFullPageContent) {
            loadContentFromUrl(url, newContent => onSuccess(newContent), error => onError(error));
          }
          else {
            loadContentPartFrom(url, newContent => onSuccess(newContent), error => onError(error));
          }
        }
        else
          showTooltip(event, tooltipText, alignment, isFullPageContent, isTextTooltip);
      });
    });

    document.addEventListener('mousemove', function (event) {
      if (shouldHideTooltip(event.target)) {
        if (tooltipTarget)
          hideTooltip(true);
      }
      else {
        clearTimeout(hideTimeoutFuncID);
        shouldShowTooltip = true;
      }
    });

    document.addEventListener('scroll', function (event) {
      if (elementUnderCursor == null || shouldHideTooltip(elementUnderCursor)) {
         hideTooltip(true);
      }
      else if (tooltipTarget) {
        var targetPosition = getElementPositionRelativeToRoot(tooltipTarget);
        var tooltipPosition = getElementPositionRelativeToRoot(contentTooltip);
        var relativPos = { 
          top: tooltipPosition.top - targetPosition.top,
          left: tooltipPosition.left - targetPosition.left
        }

        if (tooltipToTargetRelativePosition == null)
          tooltipToTargetRelativePosition = relativPos;
        else {
          // console.log(" ----");
          // console.log("tooltipPosition - Top: " + tooltipPosition.top + ", Left: " + tooltipPosition.left);
          // console.log("targetPosition - Top: " + targetPosition.top + ", Left: " + targetPosition.left);
          // console.log("relativPos - Top: " + relativPos.top + ", Left: " + relativPos.left);
          // console.log("tooltipToTargetRelativePosition - Top: " + tooltipToTargetRelativePosition.top + ", Left: " + tooltipToTargetRelativePosition.left);

          if (false == comparePositions(relativPos, tooltipToTargetRelativePosition))
            hideTooltip(true);
        }
      }      
    });

    document.addEventListener('mouseover', function (event) {
      elementUnderCursor = event.target;
    });

    window.addEventListener('resize', function () {
      if (tooltipTarget)
        hideTooltip(true);
    });

    window.addEventListener('blur', function () {
      if (tooltipTarget)
        hideTooltip(true);
    });
  }

  // -------------
  // Sticky sidebar
  // -------------

  var initiallySticky = $(".sidebar").hasClass("sticky");
  var stickySideBar = function () {
    var show =
      $(".author__urls-wrapper").find("button").length === 0
        ? $(window).width() > 1024 // width should match $large Sass variable
        : !$(".author__urls-wrapper").find("button").is(":visible");
    if (show) {
      if (initiallySticky) {
        $(".sidebar").addClass("sticky");
      }
    } else {
      $(".sidebar").removeClass("sticky");
    }
  };

  $(window).on("resize", function () {
    stickySideBar();
  });

  // -------------
  // Search
  // -------------

  if (searchEnabled) {
    // Remember the page scroll offset at the moment the search panel
    // opens so we can restore it when it closes. The search panel
    // replaces the in-flow `.initial-content` block but does not pin to
    // the viewport, so a long page scrolled near the bottom would show
    // the search panel scrolled too -- the user wouldn't see the search
    // input or the first results. Saving & restoring fixes both
    // directions (open at 0, close back to where the user was).
    var savedPageScrollY = null;
    // Also remember the scroll offset INSIDE the search panel and the
    // query that produced it. When the user reopens the panel and the
    // query is still the same (i.e. the result list is identical), we
    // restore that scroll position so they land back on the result they
    // were inspecting. If the query changes in between, we fall back to
    // scrolling to the top of the panel.
    var savedSearchScrollY = null;
    var savedSearchQuery = null;
    // Close search panel with Esc key — capture phase so stopPropagation in inner
    // elements cannot block it. Behavior is controlled by the
    // `settings-esc-behavior` cookie owned by the settings panel:
    //   - 'close'             : just close the search panel (default, current behavior)
    //   - 'close-and-clear'   : close AND wipe the query
    //   - 'clear-then-close'  : first ESC wipes a non-empty query, next ESC closes
    //
    // NOTE: the search input is `<input type="text">` (not `type="search"`)
    // precisely to avoid the browser's built-in ESC-clear, which would
    // wipe the field on `keydown` before this handler could decide what
    // to do.
    document.addEventListener('keyup', function (event) {
      if (event.keyCode === 27) {
        if ($(".initial-content").hasClass("is--hidden")) {
          var mode = (typeof getCookie === 'function')
            ? getCookie('settings-esc-behavior', 'close', true)
            : 'close';
          var input = $('#search');
          var hasText = input.length > 0 && input.val() && input.val().length > 0;

          if (mode === 'clear-then-close' && hasText) {
            input.val('');
            input.trigger('input');
            return;
          }
          if (mode === 'close-and-clear') {
            input.val('');
            input.trigger('input');
          }
          toggleSearch(event);
        }
      }
    }, true);

    // Toggle search panel with the user-configurable shortcut (default
    // Ctrl+Shift+F). The combo is stored in the `settings-hotkey-search`
    // cookie as e.g. 'Ctrl+Shift+F'; an empty value disables it.
    // Capture phase + preventDefault so the browser/OS cannot intercept
    // the combination before the page handles it.
    function eventMatchesCombo(event, combo) {
      if (!combo) return false;
      var parts = combo.split('+');
      var key = parts.pop();
      var needCtrl = parts.indexOf('Ctrl')  !== -1;
      var needShift = parts.indexOf('Shift') !== -1;
      var needAlt = parts.indexOf('Alt')   !== -1;
      var needMeta = parts.indexOf('Meta')  !== -1;
      if (!!event.ctrlKey  !== needCtrl)  return false;
      if (!!event.shiftKey !== needShift) return false;
      if (!!event.altKey   !== needAlt)   return false;
      if (!!event.metaKey  !== needMeta)  return false;
      var evKey = event.key || '';
      if (evKey.length === 1) evKey = evKey.toUpperCase();
      return evKey === key;
    }
    document.addEventListener('keydown', function (event) {
      var combo = (typeof getCookie === 'function')
        ? getCookie('settings-hotkey-search', 'Ctrl+Shift+F', true)
        : 'Ctrl+Shift+F';
      if (!eventMatchesCombo(event, combo)) return;
      event.preventDefault();
      toggleSearch(event);
    }, true);

    function toggleSearch(event) {
      // Capture the current text selection BEFORE the DOM mutations below --
      // toggling visibility / focus on the search input will collapse any
      // active selection in the page content, so we have to read it first.
      // `window.getSelection().toString()` returns plain text only (no HTML),
      // which is exactly what the search box expects.
      //
      // Gated by the `settings-prefill-selection` cookie owned by the
      // settings panel (default: enabled).
      var willOpen = !$(".search-content").hasClass("is--visible");
      var prefillEnabled = (typeof getCookie === 'function')
        ? getCookie('settings-prefill-selection', 'true', true) === 'true'
        : true;
      var selectedText = '';
      if (willOpen && prefillEnabled) {
        var sel = window.getSelection ? window.getSelection() : null;
        if (sel && sel.toString) {
          selectedText = sel.toString().replace(/\s+/g, ' ').trim();
        }
      }

      // Save (on open) / restore (on close) the page scroll position so
      // the search panel always shows from its top, and the user lands
      // back exactly where they were when they close it.
      if (willOpen) {
        savedPageScrollY = window.pageYOffset || document.documentElement.scrollTop || 0;
      }
      else {
        // About to close: capture the current panel scroll & query so we
        // can restore them on the next open (if the query stays the same).
        savedSearchScrollY = window.pageYOffset || document.documentElement.scrollTop || 0;
        savedSearchQuery = ($('#search').val() || '');
      }

      $(".search-content").toggleClass("is--visible");
      $(".search-content__form").toggleClass("is--visible");      
      $(".initial-content").toggleClass("is--hidden");
      $(".masthead").toggleClass("search-open", $(".search-content").hasClass("is--visible"));

      if (!willOpen && savedPageScrollY !== null) {
        window.scrollTo(0, savedPageScrollY);
        savedPageScrollY = null;
      }

      if ($(".initial-content").hasClass("is--hidden")) {
        // set focus on input
        setTimeout(function () {
          var input = $('#search');
          // Prefill from selection (overriding the cookie-restored value), if
          // any. Triggering `input` causes the live search handler to run
          // and surface results immediately. If nothing is selected, leave
          // the previously remembered query intact.
          if (selectedText.length > 0) {
            input.val(selectedText);
            input.trigger("input");
          }
          // Decide where to scroll inside the now-visible panel: if the
          // current query matches the one we saved on the previous close,
          // restore the previous panel scroll position so the user lands
          // on the same result. Otherwise show the panel from its top.
          var currentQuery = (input.val() || '');
          if (savedSearchQuery !== null
              && savedSearchScrollY !== null
              && currentQuery === savedSearchQuery) {
            window.scrollTo(0, savedSearchScrollY);
          }
          else {
            window.scrollTo(0, 0);
          }
          input.trigger("focus");
          input.trigger("select");
        }, 100);
      }

      if (tooltipTarget)
        hideTooltip(true);

      clearFocus();
    }

    function hideSearch() {
      var wasVisible = $(".search-content").hasClass("is--visible");
      if (wasVisible) {
        // Same panel-scroll & query capture as toggleSearch's close branch.
        savedSearchScrollY = window.pageYOffset || document.documentElement.scrollTop || 0;
        savedSearchQuery = ($('#search').val() || '');
      }
      $(".search-content").removeClass("is--visible");
      $(".search-content__form").removeClass("is--visible");
      $(".initial-content").removeClass("is--hidden");
      $(".masthead").removeClass("search-open");
      // Restore the page scroll position the user had before opening
      // the search panel (only when we actually closed something).
      if (wasVisible && savedPageScrollY !== null) {
        window.scrollTo(0, savedPageScrollY);
        savedPageScrollY = null;
      }
    }

    $("#search-button").on('click', toggleSearch);
  }

  // -------------
  // Startup
  // -------------

  stickySideBar();

  // Make sure everything is initialized correctly on an initial load as well
  // (e.g. when an inner embedded page link is opened directly in a new tab, not via the internal navigational links)
  finalizeContent();

  hideSearch();

  // Listen for popstate events and update content accordingly
  window.addEventListener('popstate', function () {
    updateContentFromUrl(window.location.pathname);
  });

  window.searchResultLinkClickHandler = function (event) {
    // Do NOT call hideSearch() up front: it would remove `.is--hidden` from
    // `.initial-content` immediately, revealing the still-old page for the
    // full duration of the fetch + 100 ms swap timeout in updateContentFromUrl.
    // finalizeContent() calls hideSearch() at the very end of the SPA swap
    // (after the new article is in the DOM and the anchor jump has happened),
    // so the search overlay stays put until the new content is ready.
    handleNavLinkClick(event);
  };
});
